spring.application.name=Daily-Book

# Let Render decide port, use 8080 locally
server.port=${PORT:8080}

# HARD-CODED MONGODB ATLAS URI
spring.data.mongodb.uri=mongodb+srv://dailyBook_admin_:asjh1232348akjskaCSDJ56F@dailybook.kb0aaqu.mongodb.net/dailybookdb?appName=DailyBook


# JWT CONFIG
jwt.secret=${JWT_SECRET:Y2hhbmdlLXlvdXItanZ0LXNlY3JldC1rZXktd2l0aC1hdC1sZWFzdC0zMi1ieXRlcy1sb25nLWZvb2Jhcg==}
jwt.expiration=${JWT_EXPIRATION:3600000}
