spring.application.name=Daily-Book

# Let Render decide port, use 8080 locally
server.port=${PORT:8080}

# MongoDB Atlas URI will come from Render env variable
spring.data.mongodb.uri=${MONGODB_URI}

# JWT CONFIG (also from env, with defaults)
jwt.secret=${JWT_SECRET:Y2hhbmdlLXlvdXItanZ0LXNlY3JldC1rZXktd2l0aC1hdC1sZWFzdC0zMi1ieXRlcy1sb25nLWZvb2Jhcg==}
jwt.expiration=${JWT_EXPIRATION:7L * 24 * 60 * 60 * 1000}
